name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - run: npx nx run-many -t build --parallel=2

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - run: npx nx run-many -t typecheck --parallel=2

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - run: npx nx format:check --base="remotes/origin/main"
      - run: npx nx run-many -t lint --parallel=2

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - run: npx nx run-many -t test --parallel=2

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npx nx run-many -t e2e --parallel=1 --output-style=stream -- --workers=1
